esclarecimento/urls.py
from django.urls import path,include
from . import views
app_name='esclarecimento'
urlpatterns = [
    path('',views.index,name='index'),
    path('add_esclarecimento',views.add_escla,name='add_escla'),
    path('<int:id>/adicionar_mensagem',views.adicionar_chat,name='add_chat'),
    path('<int:id>/identificar_obra',views.identificar_obra,name='id_obra'),
]

login/urls.py
from django.urls import path,include
from . import views
app_name='login'
urlpatterns = [
    path('',views.index,name='index'),
]

obras/urls.py
from django.urls import path,include
from . import views
app_name='obras'
urlpatterns = [
    path('',views.index,name='index'),
]

quanto_custa/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('obras/',include('obras.urls',namespace='obras')),
    path('esclarecimento/',include('esclarecimento.urls',namespace='esclarecimento')),
    path('login/',include('login.urls',namespace='login')),

]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

esclarecimento/models.py
from django.db import models
from obras.models import Obra
from django.contrib.auth.models import User
# Create your models here.

class Esclarecimento(models.Model):
    titulo = models.CharField(max_length=255)
    descricao = models.TextField(null=True)
    gps_lat = models.DecimalField(max_digits=9,decimal_places=6,null=True)
    gps_long = models.DecimalField(max_digits=9,decimal_places=6,null=True)
    data_criado = models.DateTimeField(auto_now_add=True)
    obra = models.ForeignKey(Obra,on_delete=models.PROTECT,null=True)
    autor = models.ForeignKey(User,on_delete=models.PROTECT)
    ABERTO = 1
    PROCESSANDO = 2
    FINALIZADO = 3
    status_choices = (
        (ABERTO, 'Não tem novidades'),
        (PROCESSANDO, 'Deram andamento'),
        (FINALIZADO, 'Finalizado'),
    )
    status = models.IntegerField(choices=status_choices,null=True)

    def get_foto_principal(self):
        dado = self.foto_esclarecimento_set.filter(principal=True).first()
        if dado is not None:
            dado = dado.foto
            return dado
        else:
            dado = None
            return False

    def status_css(self):

        if self.status==None:
            return "abrt"
        if self.status == self.ABERTO:
            return "abrt"
        if self.status == self.PROCESSANDO:
            return "andt"
        if self.status == self.FINALIZADO:
            return "fchd"


class Chat(models.Model):
    esclarecimento = models.ForeignKey(Esclarecimento,on_delete=models.PROTECT)
    mensagem=models.TextField(null=True)
    data_criado = models.DateTimeField(auto_now_add=True)
    autor=models.ForeignKey(User,on_delete=models.PROTECT)

class Foto(models.Model):
    foto = models.ImageField(upload_to='fotos/',null=True)
    data_criado = models.DateTimeField(auto_now_add=True)
    autor = models.ForeignKey(User,on_delete=models.PROTECT)


class Foto_Esclarecimento(models.Model):
    esclarecimento = models.ForeignKey(Esclarecimento,on_delete=models.PROTECT)
    foto = models.ForeignKey(Foto,on_delete=models.PROTECT)
    principal = models.BooleanField(null=True)

login/models.py
from django.db import models

# Create your models here.

obras/models.py
from django.db import models
from quanto_custa.utilidades import remover_acento
# Create your models here.

class Empresa(models.Model):
    razao_social=models.CharField(max_length=255)
    razao_social_sem_acento=models.CharField(max_length=255,null=True)
    cnpj=models.CharField(max_length=25)
    informacoes_adicionais = models.TextField(null=True)

    def save(self,*args,**kwargs):
        self.razao_social_sem_acento = remover_acento(self.razao_social)
        super(Empresa, self).save(*args,**kwargs)

class Obra(models.Model):
    descricao = models.CharField(max_length=255,null=True)
    data_inicial = models.DateField(null=True)
    data_final = models.DateField(null=True)
    orcado = models.DecimalField(max_digits=128,decimal_places=2)
    informacoes_adicionais = models.TextField(null=True)
    empresa = models.ForeignKey(Empresa,on_delete=models.PROTECT,null=True)

esclarecimento/views.py
from django.shortcuts import render
from django.template import loader
from django.shortcuts import render
from django.http import HttpResponse
from .models import Esclarecimento,Chat
from .utilidades import get_reclamacao_post,get_chat
from obras.utilidades import get_obra_post
# Create your views here.
def index(request):
    template = loader.get_template("index.html")
    context={}

    if request.method=="GET":

        esclarecimentos = Esclarecimento.objects.all()
        context.update(esclarecimentos=esclarecimentos)

        return HttpResponse(template.render(context,request))
    else:
        esclarecimento,mensagem_erro=get_reclamacao_post(request=request)
        context.update(esclarecimento=esclarecimento)

        chats = Chat.objects.filter(esclarecimento_id=esclarecimento.id).order_by('-id')
        context.update(chats=chats)

        template = loader.get_template("comentario.html")
        return HttpResponse(template.render(context,request))

def add_escla(request):
    template = loader.get_template("form.html")
    context={}

    if request.method=="GET":

        esclarecimentos = Esclarecimento.objects.all()
        context.update(esclarecimentos=esclarecimentos)

        return HttpResponse(template.render(context,request))
    else:
        esclarecimento,mensagem_erro=get_reclamacao_post(request=request)
        context.update(esclarecimento=esclarecimento)

        chats = Chat.objects.filter(esclarecimento_id=esclarecimento.id).order_by('-id')
        context.update(chats=chats)

        template = loader.get_template("comentario.html")
        return HttpResponse(template.render(context,request))

def adicionar_mensagem(request,id):

    pass

def adicionar_chat(request,id):
    template = loader.get_template("comentario.html")
    context={}

    esclarecimento=Esclarecimento.objects.get(id=id)
    context.update(esclarecimento=esclarecimento)

    if request.method=="GET":
        pass

    else:
        chat,mensagem_erro = get_chat(request,esclarecimento)

    chats = Chat.objects.filter(esclarecimento_id=esclarecimento.id).order_by('-id')
    context.update(chats=chats)

    return HttpResponse(template.render(context,request))


def identificar_obra(request,id):
    template = loader.get_template("template_identificar_obra.html")
    context={}

    esclarecimento = Esclarecimento.objects.get(id=id)


    if request.method == "GET":
        context.update(esclarecimento=esclarecimento)

    else:
        obra = get_obra_post(request)
        esclarecimento.obra=obra
        esclarecimento.save()
        context.update(esclarecimento=esclarecimento)

    return HttpResponse(template.render(context,request))

login/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    pass

obras/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return None

esclarecimento/templates/comentario.html
{% load static %}
<!doctype html>
<html lang="pt">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Comentarios</title>
  <link rel="stylesheet" href="{% static 'comentario.css' %}">
</head>
<body>
  <div id="poste">
          <div class="poste-padding">
            <div clas="poste-content">
              <div class="img-poste-obra"><img class="img-poste" src="{{esclarecimento.get_foto_principal.foto.url}}"></div>
              <div class="desc-poste">
                  <h1>{{esclarecimento.titulo}}</h1>
                  <h2> {{esclarecimento.descricao}}</h2>

              </div>
              <div class="coment-poste">
                <div class="title-coment"><p>MAIS RECENTES</p></div>
                <div class="conteiner-coment">
                  <div class="topico"></div>
                  {% for chat in chats %}
                  <div class="comentarios">
                      <div class="img-coment-perfil"><img class="img-perfil" src="{% static 'perfil.jpg' %}" /></div>
                      <div class="texto-coment"><p>{{chat.mensagem}}</p></div>
                  </div>
                  {% endfor %}

                  <div class="comentarios">
                    <div class="title-coment"><p>Deixe seu comentario</p></div>
                    <form class="" action="{% url 'esclarecimento:add_chat' id=esclarecimento.id %}" method="POST">
                      {% csrf_token %}
                      {% if not request.user.is_authenticated %}
                      <div><input class="campo-email" type="text" placeholder="Digite Seu E-mail" name="email"></div>
                      {% endif %}
                      <div><input class="campo-comentario" type="text" placeholder="Digite Seu comentario" name="mensagem"></div>

                      <div>
                        <button class="enviar" type="submit" value="Enviar" name="enviar">Enviar</button>

                      </div>
                    </form>
                 </div>

                </div>
              </div>
            </div>
          </div>
  </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

esclarecimento/templates/descricao.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Esclarece Aqui</title>
  <link rel="stylesheet" href="css/main.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt"
    crossorigin="anonymous">
</head>

<body>
  <header>
    <nav class="menu">
      <h1 class="menu-branding">
        <a href="index.html">esclarece aqui</a>
      </h1>
      <ul class="menu-nav">
        <li class="nav-item">
          <a href="blog.html" class="nav-link">login</a>
        </li>
      </ul>
    </nav>
  </header>

  <main id="form">
    <form action="" enctype="multipart/form-data">
        <div class="container">
            <h2>INFORMAÇÕES DA OBRA</h2>

            <label for="descricao"><b>Descrição</b></label>
            <textarea name="descricao" cols="40" rows="5" required></textarea>

            <label for="dtinic"><b>Data inicial</b></label>
            <input type="text" name="dtinic">

            <label for="dtfinal"><b>Data final</b></label>
            <input type="text" name="dtfinal">

            <label for="valor"><b>Valor orçado</b></label>
            <input type="text" name="valor">

            <label for="mais-info"><b>Mais informações da obra</b></label>
            <textarea name="mais-info" cols="40" rows="5" required></textarea>

            <hr>
            
            <h2>INFORMAÇÕES DA EMPRESA</h2>

            <label for="rz-social"><b>Razão social</b></label>
            <input type="text" name="rz-social">

            <label for="cnpj"><b>CNPJ</b></label>
            <input type="text" name="cnpj">

            <label for="mais-emp"><b>Adicionais da empresa</b></label>
            <textarea name="mais-emp" cols="40" rows="5" required></textarea>

            <button type="submit" class="enviar">Enviar requisição</button>
        </div>
    </form>
  </main>
</body>
</html>

esclarecimento/templates/form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Esclarece Aqui</title>
  <link rel="stylesheet" href="{% static 'main.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt"
    crossorigin="anonymous">
</head>

<body>
  <header>
    <nav class="menu">
      <h1 class="menu-branding">
        esclarece aqui
      </h1>
      <ul class="menu-nav">
        <li class="nav-item">
          <a href="blog.html" class="nav-link">login</a>
        </li>
      </ul>
    </nav>
  </header>

  <main id="form">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <form action="{% url 'esclarecimento:index' %} " method="POST" enctype="multipart/form-data">
      {% csrf_token %}
        <div class="container">
            <label for="titulo"><b>Titulo</b></label>
            <input type="text" name="titulo" value="{{esclarecimento.titulo}}" required>

            <label for="descricao"><b>Descrição</b></label>
            <textarea name="descricao" cols="40" rows="5" required>{{esclarecimento.descricao}}</textarea>

            <label for="email"><b>Email</b></label>
            <input type="email" name="email" value="{{esclarecimento.autor.email}}" required>

            <div class="img">
                <label for="file-upload1" class="custom-file-upload">Foto da placa</label>
                <input id="file-upload1" name='foto_placa' type="file">

                <label for="file-upload2" class="custom-file-upload">Foto da obra</label>
                <input id="file-upload2" name='foto_obra' type="file">
            </div>

            <button type="submit" class="enviar">Enviar requisição</button>
        </div>
    </form>
  </main>

  <script src="{% static 'main.js' %}"></script>
</body>
</html>

esclarecimento/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Esclarece Aqui</title>
  <link rel="stylesheet" href="{% static "main.css" %}">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt"
    crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flexboxgrid/6.3.1/flexboxgrid.min.css" type="text/css" >
</head>

<body>
  <header>
    <nav class="menu">
      <h1 class="menu-branding">
        esclarece aqui
      </h1>
      <ul class="menu-nav">
        <li class="nav-item">
          <a href="blog.html" class="nav-link">login</a>
        </li>
      </ul>
    </nav>
  </header>

  <main id="home">
    <div class="bar">
      <div class="esquerda">
        <button class="aberta">Abertas</button>
        <button class="fechada">Fechadas</button>
        <button class="andamento">Em andamento</button>
      </div>
      <div class="direita">
        <button id="grid"><i class="fa fa-th-large"></i></button>
        <button id="list"><i class="fa fa-bars"></i></button>
      </div>
    </div>
    <div class="adiciona">
      {# <a id="add" href="#">Testes</a> #}
      <a href="{% url 'esclarecimento:add_escla' %}">
        <button id="add">Solicitar esclarecimento</button>
      </a>
    </div>
    <div id="card-block" class="show-grid">
    {% if False %}
      <div class="card-img" style="background-image: url({% static "outdoor1.jpeg" %});">
        <a href="#" class="card-url">
          <div class="card abrt">
            <h2>Titulo</h2>
            <h4 class="hidden">Endereco</h4>
          </div>
        </a>
      </div>

      <div class="card-img" style="background-image: url({% static "outdoor2.jpeg" %});">
        <a href="#" class="card-url">
          <div class="card fchd">
            <h2>Titulo</h2>
            <h4 class="hidden">Endereco</h4>
          </div>
        </a>
      </div>

      <div class="card-img" style="background-image: url({% static "outdoor3.jpg" %});">
        <a href="#" class="card-url">
          <div class="card andt">
            <h2>Titulo</h2>
            <h4 class="hidden">Endereco</h4>
          </div>
        </a>
      </div>
      {% else %}
      {% for esclarecimento in esclarecimentos  %}
      {% if esclarecimento.id == 8 %}
      <a href="{% url 'esclarecimento:add_chat' id=esclarecimento.id %}" class="card-url">
        <div class="card abrt" style="background-image: url({% if esclarecimento.get_foto_principal %}{{esclarecimento.get_foto_principal.foto.url}}{% endif %});">
          <h2>{{esclarecimento.titulo}}</h2>
          <h4 class="hidden">{{esclarecimento.descricao}}</h4>
        </div>
      </a>
      {% endif %}
      {% if esclarecimento.id == 9 %}
      <a href="{% url 'esclarecimento:add_chat' id=esclarecimento.id %}" class="card-url">
        <div class="card fchd" style="background-image: url({% if esclarecimento.get_foto_principal %}{{esclarecimento.get_foto_principal.foto.url}}{% endif %});">
          <h2>{{esclarecimento.titulo}}</h2>
          <h4 class="hidden">{{esclarecimento.descricao}}</h4>
        </div>
      </a>
      {% endif %}
      {% if esclarecimento.id == 10 %}
      <a href="{% url 'esclarecimento:add_chat' id=esclarecimento.id %}" class="card-url">
        <div class="card andt" style="background-image: url({% if esclarecimento.get_foto_principal %}{{esclarecimento.get_foto_principal.foto.url}}{% endif %});">
          <h2>{{esclarecimento.titulo}}</h2>
          <h4 class="hidden">{{esclarecimento.descricao}}</h4>
        </div>
      </a>
      {% endif %}
      {% if esclarecimento.id > 10 %}
      <a href="{% url 'esclarecimento:add_chat' id=esclarecimento.id %}" class="card-url">
        <div class="card {{esclarecimento.status_css}}" style="background-image: url({% if esclarecimento.get_foto_principal %}{{esclarecimento.get_foto_principal.foto.url}}{% endif %});">
          <h2>{{esclarecimento.titulo}}</h2>
          <h4 class="hidden">{{esclarecimento.descricao}}</h4>
        </div>
      </a>
      {% endif %}
      {% endfor %}
      {% endif %}
    </div>
  </main>

  <script src="{% static "button.js" %}"></script>
</body>

</html>

<!-- https://stackoverflow.com/questions/41542845/how-to-display-file-name-for-custom-styled-input-file-using-jquery -->

esclarecimento/templates/index2.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Esclarece Aqui</title>
  <link rel="stylesheet" href="css/main.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt"
    crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flexboxgrid/6.3.1/flexboxgrid.min.css" type="text/css" >
</head>

<body>
  <header>
    <nav class="menu">
      <h1 class="menu-branding">
        esclarece aqui
      </h1>
      <ul class="menu-nav">
        <li class="nav-item">
          <a href="blog.html" class="nav-link">login</a>
        </li>
      </ul>
    </nav>
  </header>

  <main id="home">
    <div class="bar">
      <div class="esquerda">
        <button class="aberta">Abertas</button>
        <button class="fechada">Fechadas</button>
        <button class="andamento">Em andamento</button>
      </div>
      <div class="direita">
        <button id="grid"><i class="fa fa-th-large"></i></button>
        <button id="list"><i class="fa fa-bars"></i></button>
      </div>
    </div>
    <div class="adiciona">
      <button id="add">Solicitar esclarecimento</button>
    </div>

    <div id="card-block" class="show-grid">
      <a href="#" class="card-url">
        <div class="card abrt" style="background-image: url(../img/outdoor1.jpeg);">
          <h2>Titulo</h2>
          <h4 class="hidden">Endereco</h4>
        </div>
      </a>

      <a href="#" class="card-url">
        <div class="card fchd" style="background-image: url(../img/outdoor2.jpeg);">
          <h2>Titulo</h2>
          <h4 class="hidden">Endereco</h4>
        </div>
      </a>

      <a href="#" class="card-url">
        <div class="card andt" style="background-image: url(../img/outdoor3.jpg);">
          <h2>Titulo</h2>
          <h4 class="hidden">Endereco</h4>
        </div>
      </a>

      <a href="#" class="card-url">
        <div class="card andt" style="background-image: url(../img/outdoor4.jpeg);">
          <h2>Titulo</h2>
          <h4 class="hidden">Endereco</h4>
        </div>
      </a>
    </div>
  </main>

  <script src="js/button.js"></script>
</body>

</html>

<!-- https://stackoverflow.com/questions/41542845/how-to-display-file-name-for-custom-styled-input-file-using-jquery -->

esclarecimento/templates/temp.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Esclarece Aqui</title>
  <link rel="stylesheet" href="css/main.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt"
    crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flexboxgrid/6.3.1/flexboxgrid.min.css" type="text/css" >
</head>

<body>
  <header>
    <nav class="menu">
      <h1 class="menu-branding">
        esclarece aqui
      </h1>
      <ul class="menu-nav">
        <li class="nav-item">
          <a href="blog.html" class="nav-link">login</a>
        </li>
      </ul>
    </nav>
  </header>

  <main id="home">
    <div class="bar">
      <div class="esquerda">
        <button class="aberta">Abertas</button>
        <button class="fechada">Fechadas</button>
        <button class="andamento">Em andamento</button>
      </div>
      <div class="direita">
        <button id="grid"><i class="fa fa-th-large"></i></button>
        <button id="list"><i class="fa fa-bars"></i></button>
      </div>
    </div>
    <div class="adiciona">
      <button id="add">Solicitar esclarecimento</button>
    </div>

    <div id="card-block" class="show-grid">
      <a href="#" class="card-url">
        <div class="card abrt" style="background-image: url(../img/outdoor1.jpeg);">
          <h2>Titulo</h2>
          <h4 class="hidden">Endereco</h4>
        </div>
      </a>

      <a href="#" class="card-url">
        <div class="card fchd" style="background-image: url(../img/outdoor2.jpeg);">
          <h2>Titulo</h2>
          <h4 class="hidden">Endereco</h4>
        </div>
      </a>

      <a href="#" class="card-url">
        <div class="card andt" style="background-image: url(../img/outdoor3.jpg);">
          <h2>Titulo</h2>
          <h4 class="hidden">Endereco</h4>
        </div>
      </a>

      <a href="#" class="card-url">
        <div class="card andt" style="background-image: url(../img/outdoor4.jpeg);">
          <h2>Titulo</h2>
          <h4 class="hidden">Endereco</h4>
        </div>
      </a>
    </div>
  </main>

  <script src="js/button.js"></script>
</body>

</html>

<!-- https://stackoverflow.com/questions/41542845/how-to-display-file-name-for-custom-styled-input-file-using-jquery -->

login/templates/card_fundo.html
<div class="card">
  <div class="card-header">
    Configurar o Fundo
  </div>
  <div class="card-body">
    {% if fundo %}
    <input type="hidden" name="id" value="{{fundo.id}}" />
    {% endif %}

      <div class="row">
        <div class="col-md-8">
          <div class="form-group">
            <label for="nome">Nome</label>
            <input type="text" class="form-control" name="nome" value="{{fundo.nome}}"/>
          </div>
          <div class="form-group">
            <label for="id_banner">Foto de Fundo</label>
            <input type="file" class="form-control" id="id_banner" name="foto_pagina"/>
          </div>
          <div class="form-group">
            {% if fundo %}
            <button type="submit" class="btn btn-primary form-control">Atualizar</button>
            {% else %}
            <button type="submit" class="btn btn-primary form-control">Adicionar</button>
            {% endif %}
          </div>
        </div>
        <div class="col-md-4">
          {% if fundo %}
            <img src="{{fundo.dado.url}}" class="img-fluid" alt="Responsive image">
          {% else %}

          {% endif %}
        </div>
      </div>

  </div>
</div>

obras/templates/card_fundo.html
<div class="card">
  <div class="card-header">
    Configurar o Fundo
  </div>
  <div class="card-body">
    {% if fundo %}
    <input type="hidden" name="id" value="{{fundo.id}}" />
    {% endif %}

      <div class="row">
        <div class="col-md-8">
          <div class="form-group">
            <label for="nome">Nome</label>
            <input type="text" class="form-control" name="nome" value="{{fundo.nome}}"/>
          </div>
          <div class="form-group">
            <label for="id_banner">Foto de Fundo</label>
            <input type="file" class="form-control" id="id_banner" name="foto_pagina"/>
          </div>
          <div class="form-group">
            {% if fundo %}
            <button type="submit" class="btn btn-primary form-control">Atualizar</button>
            {% else %}
            <button type="submit" class="btn btn-primary form-control">Adicionar</button>
            {% endif %}
          </div>
        </div>
        <div class="col-md-4">
          {% if fundo %}
            <img src="{{fundo.dado.url}}" class="img-fluid" alt="Responsive image">
          {% else %}

          {% endif %}
        </div>
      </div>

  </div>
</div>